-- -------------------------------------------------------------
-- 
-- File Name: tp_vivado\hdlsrc\main\detector_flancos.vhd
-- Created: 2022-12-09 14:11:09
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: detector_flancos
-- Source Path: main/Subsystem/detector_flancos
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY detector_flancos IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rxd                               :   IN    std_logic;  -- ufix1
        flanco                            :   OUT   std_logic
        );
END detector_flancos;


ARCHITECTURE rtl OF detector_flancos IS

  -- Signals
  SIGNAL Delay_out1                       : std_logic;  -- ufix1
  SIGNAL Delay1_out1                      : std_logic;  -- ufix1
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL AND_out1                         : std_logic;

BEGIN
  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= rxd;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  NOT_out1 <=  NOT Delay_out1;

  AND_out1 <= Delay1_out1 AND NOT_out1;

  flanco <= AND_out1;

END rtl;

