-- -------------------------------------------------------------
-- 
-- File Name: tp_vivado\hdlsrc\main\Difference.vhd
-- Created: 2022-12-09 14:11:09
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Difference
-- Source Path: main/Subsystem/generador_pulsos_ad/Difference
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Difference IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Y                                 :   OUT   std_logic_vector(8 DOWNTO 0)  -- sfix9
        );
END Difference;


ARCHITECTURE rtl OF Difference IS

  -- Signals
  SIGNAL U_unsigned                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL U_k_1                            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Diff_sub_cast                    : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Diff_sub_cast_1                  : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Diff_out1                        : signed(8 DOWNTO 0);  -- sfix9

BEGIN
  -- ( U(k) - U(k-1) )
  -- U(k)

  U_unsigned <= unsigned(U);

  -- 
  -- Store in Global RAM
  UD_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= U_unsigned;
      END IF;
    END IF;
  END PROCESS UD_process;


  -- 
  -- Add in CPU
  Diff_sub_cast <= signed(resize(U_unsigned, 9));
  Diff_sub_cast_1 <= signed(resize(U_k_1, 9));
  Diff_out1 <= Diff_sub_cast - Diff_sub_cast_1;

  Y <= std_logic_vector(Diff_out1);

END rtl;

