-- -------------------------------------------------------------
-- 
-- File Name: tp_vivado\hdlsrc\main\generador_pulsos_ad.vhd
-- Created: 2022-12-09 14:11:09
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: generador_pulsos_ad
-- Source Path: main/Subsystem/generador_pulsos_ad
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY generador_pulsos_ad IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rd_dout                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dato_wr_ad                        :   OUT   std_logic
        );
END generador_pulsos_ad;


ARCHITECTURE rtl OF generador_pulsos_ad IS

  -- Component Declarations
  COMPONENT Difference
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Y                               :   OUT   std_logic_vector(8 DOWNTO 0)  -- sfix9
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Difference
    USE ENTITY work.Difference(rtl);

  -- Signals
  SIGNAL rd_dout_unsigned                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL dato_wr_ad_1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Difference_out1                  : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Difference_out1_signed           : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL NOT2_out1                        : std_logic;
  SIGNAL dato_wr_ad_2                     : std_logic;
  SIGNAL dato_wr_ad_3                     : std_logic;
  SIGNAL dato_wr_ad_4                     : std_logic;
  SIGNAL dato_wr_ad_5                     : std_logic;
  SIGNAL dato_wr_ad_6                     : std_logic;
  SIGNAL NOT1_out1                        : std_logic;

BEGIN
  u_Difference : Difference
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              U => std_logic_vector(dato_wr_ad_1),  -- uint8
              Y => Difference_out1  -- sfix9
              );

  rd_dout_unsigned <= unsigned(rd_dout);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dato_wr_ad_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dato_wr_ad_1 <= rd_dout_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Difference_out1_signed <= signed(Difference_out1);

  
  Compare_To_Zero_out1 <= '1' WHEN Difference_out1_signed = to_signed(16#000#, 9) ELSE
      '0';

  NOT2_out1 <=  NOT Compare_To_Zero_out1;

  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dato_wr_ad_2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dato_wr_ad_2 <= NOT2_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dato_wr_ad_3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dato_wr_ad_3 <= dato_wr_ad_2;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  dato_wr_ad_4 <= dato_wr_ad_2 OR dato_wr_ad_3;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dato_wr_ad_5 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dato_wr_ad_5 <= dato_wr_ad_3;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  dato_wr_ad_6 <= dato_wr_ad_4 OR dato_wr_ad_5;

  NOT1_out1 <=  NOT dato_wr_ad_6;

  dato_wr_ad <= NOT1_out1;

END rtl;

