-- -------------------------------------------------------------
-- 
-- File Name: tp_vivado\hdlsrc\main\reloj_sicnronizador.vhd
-- Created: 2022-12-09 14:11:09
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: reloj_sicnronizador
-- Source Path: main/Subsystem/reloj_sicnronizador
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY reloj_sicnronizador IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Enable_Input                      :   IN    std_logic;
        Threshold                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        muestras_max                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        pulsos                            :   OUT   std_logic
        );
END reloj_sicnronizador;


ARCHITECTURE rtl OF reloj_sicnronizador IS

  -- Signals
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant1_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Threshold_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add_out1                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add_out1_dtc                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Less_Than_relop1                 : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch1_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL muestras_max_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Less_Than1_relop1                : std_logic;

BEGIN
  
  switch_compare_1 <= '1' WHEN Enable_Input > '0' ELSE
      '0';

  Constant1_out1 <= to_unsigned(0, 32);

  Constant_out1 <= to_unsigned(1, 32);

  Threshold_unsigned <= unsigned(Threshold);

  Add_out1_dtc <= resize(Add_out1, 32);

  Add_out1 <= resize(resize(Delay_out1, 33) + resize(Constant_out1, 33), 16);

  
  Less_Than_relop1 <= '1' WHEN resize(Add_out1, 32) <= Threshold_unsigned ELSE
      '0';

  
  switch_compare_1_1 <= '1' WHEN Less_Than_relop1 > '0' ELSE
      '0';

  
  Switch_out1 <= Constant1_out1 WHEN switch_compare_1_1 = '0' ELSE
      Add_out1_dtc;

  
  Switch1_out1 <= Constant1_out1 WHEN switch_compare_1 = '0' ELSE
      Switch_out1;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  muestras_max_unsigned <= unsigned(muestras_max);

  
  Less_Than1_relop1 <= '1' WHEN Delay_out1 = muestras_max_unsigned ELSE
      '0';

  pulsos <= Less_Than1_relop1;

END rtl;

