-- -------------------------------------------------------------
-- 
-- File Name: tp_vivado\hdlsrc\main\Subsystem_pkg.vhd
-- Created: 2022-12-09 14:11:09
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Subsystem_pkg IS
  TYPE T_state_type_is_contador_mem_rd IS (IN_Espera, IN_Reset, IN_incrementa, IN_inicio);
  TYPE T_state_type_is_contador_mem_wr IS (IN_Espera, IN_Reset, IN_incrementa, IN_inicio);
  TYPE T_state_type_is_rconversor_uart_uint IS (IN_E_espera, IN_E_espera2, IN_e_fin, IN_e_inicio, IN_e_reposo, IN_e_rota);
END Subsystem_pkg;

